import jsPDF from 'jspdf';

/**
 * Generates and downloads a Doctor's Note PDF.
 * @param {Object} options
 * @param {string} options.patientName - The patient's name.
 * @param {string} options.adviceSummary - The summary of advice given.
 * @param {string|Date} [options.date] - The date of the session (defaults to today).
 */
export function generateDoctorNotePDF({ patientName, adviceSummary, date }) {
  const doc = new jsPDF();
  const sessionDate = date ? new Date(date) : new Date();
  const formattedDate = sessionDate.toLocaleDateString();

  doc.setFontSize(18);
  doc.text("Doctor's Note", 105, 20, { align: 'center' });

  doc.setFontSize(12);
  doc.text(`Patient Name: ${patientName || '________________'}`, 20, 40);
  doc.text(`Date: ${formattedDate}`, 20, 50);

  doc.setFontSize(14);
  doc.text('Summary of Advice:', 20, 70);
  doc.setFontSize(12);
  let cleanSummary = (adviceSummary || '________________')
    .replace(/\*\*/g, '')
    .replace(/Patient Notes:/g, 'Patient Symptoms:');
  doc.text(cleanSummary, 20, 80, { maxWidth: 170 });

  doc.setFontSize(10);
  doc.text('This note was generated by Dr. Ava, your virtual medical assistant.', 20, 120);

  doc.save(`Doctors_Note_${patientName ? patientName.replace(/\s+/g, '_') : 'Patient'}_${formattedDate.replace(/\//g, '-')}.pdf`);
} 